{% set conda_version = "23.10.0" %}
{% set conda_libmamba_solver_version = "23.11.0" %}
{% set libmambapy_version = "1.5.3" %}
{% set constructor_version = "3.5.0" %}
{% set python_version = "3.9.15" %}

package:
  name: conda-standalone
  version: {{ version }}

source:
  - url: https://github.com/conda/conda-standalone/archive/{{ version }}.tar.gz
    sha256: 819fc8ee8522707a93fc15cf823bb8aa3bc57fc5255ed3efd2f61209e0ed2c86

  - url: https://github.com/conda/conda/archive/{{ version }}.tar.gz
    sha256: 273d49db8ea723426b87866381daf2df27c7bca2c3474196460d637b62de2a1c
    folder: conda_src
    patches:
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch"
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch"
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0003-Return-unknown-module-in-deprecations.patch"

  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: 787ffd85e9414bdf70fe531f01eab3987a040e3f6a6ac3a01409f4d332f7de9e  # [win]
    folder: constructor_src  # [win]

build:
  number: 0
  ignore_run_exports:
    - '*'

requirements:
  build:
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ version }}
    - conda-package-handling >=1.6
    - menuinst >=1.4.18,<2.0a0  # [win]
    - conda-libmamba-solver ={{ conda_libmamba_solver_version }}
    - libmambapy ={{ libmambapy_version }}
  run_constrained:
    - constructor >={{ constructor_version }}

test:
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -vv

about:
  home: https://github.com/conda/conda-standalone
  license: LicenseRef-CondaStandalone
  license_file:
    - LICENSE
    - 3rd-party-licenses.json
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.

extra:
  recipe-maintainers:
    - jaimergp
    - jakirkham
    - msarahan
    - forrestwaters
    - nehaljwani
