{% set version = "24.11.0" %}
{% set conda_libmamba_solver_version = "24.9.0" %}
{% set libmambapy_version = "1.5.11" %}
{% set constructor_version = "3.10.0" %}
{% set menuinst_lower_bound = "2.2.0" %}
{% set python_version = "3.11.10" %}

package:
  name: conda-standalone
  version: {{ version }}

source:
  - url: https://github.com/conda/conda-standalone/archive/{{ version }}.tar.gz
    sha256: 195a13539c1e048a7ce3a3b74e5f6c30813ec339cf811e407f83076d8ecafd83

  - url: https://github.com/conda/conda/archive/{{ version }}.tar.gz
    sha256: 781cfe0d1bcc8d6f0249ea58a7f9655a5089a8a6eeab1511ab556e6a8e742e23
    folder: conda_src
    patches:
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch"
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch"
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0003-Restrict-search-paths.patch"


  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: cfb77a5e64b5b2b44fdb5c3d04adbb652c1249a86ea2e88f9b293e367a809caf  # [win]
    folder: constructor_src  # [win]

build:
  number: 0
  ignore_run_exports:
    - '*'
  script_env:
    - PYINSTALLER_CONDARC_DIR={{ RECIPE_DIR }}

requirements:
  build:
    - {{ stdlib('c') }}  # [osx and x86_64]
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ version }}
    - conda-package-handling >=2.3.0
    - conda-package-streaming >=0.9.0
    - menuinst >={{ menuinst_lower_bound }}
    - conda-libmamba-solver ={{ conda_libmamba_solver_version }}
    - libmambapy ={{ libmambapy_version }}
    - archspec >=0.2.3
  run_constrained:
    - constructor >={{ constructor_version }}

test:
  requires:
    - conda
    - pytest
    - menuinst >={{ menuinst_lower_bound }}
    - ruamel.yaml
  source_files:
    - tests
  commands:
    - pytest -vv
    - test ! -f {{ PREFIX }}/bin/codesign  # [osx]

about:
  home: https://github.com/conda/conda-standalone
  license: LicenseRef-CondaStandalone
  license_file:
    - LICENSE
    - 3rd-party-licenses.json
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.

extra:
  recipe-maintainers:
    - jaimergp
    - jakirkham
    - msarahan
    - forrestwaters
    - nehaljwani
