{% set conda_version = "23.11.0" %}
{% set conda_libmamba_solver_version = "23.12.0" %}
{% set libmambapy_version = "1.5.3" %}
{% set constructor_version = "3.6.0" %}
{% set python_version = "3.10.13" %}

package:
  name: conda-standalone
  version: {{ version }}

source:
  - url: https://github.com/conda/conda-standalone/archive/{{ version }}.tar.gz
    sha256: 9276686c8a6ee536dc451cc6557685724fe275a44949ac4f741066fd23cdc7b4

  - url: https://github.com/conda/conda/archive/{{ version }}.tar.gz
    sha256: 273d49db8ea723426b87866381daf2df27c7bca2c3474196460d637b62de2a1c
    folder: conda_src
    patches:
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch"
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch"
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0003-Return-unknown-module-in-deprecations.patch"

  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: d47e6f805337de70a72dea62999853361fbf558e2fbf3a9016c7a007be82ff46  # [win]
    folder: constructor_src  # [win]

build:
  number: 0
  ignore_run_exports:
    - '*'

requirements:
  build:
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ version }}
    - conda-package-handling >=1.6
    - menuinst >=2.0.2
    - conda-libmamba-solver ={{ conda_libmamba_solver_version }}
    - libmambapy ={{ libmambapy_version }}
  run_constrained:
    - constructor >={{ constructor_version }}

test:
  requires:
    - pytest
    - menuinst >=2.0.2
  source_files:
    - tests
  commands:
    - pytest -vv

about:
  home: https://github.com/conda/conda-standalone
  license: LicenseRef-CondaStandalone
  license_file:
    - LICENSE
    - 3rd-party-licenses.json
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.

extra:
  recipe-maintainers:
    - jaimergp
    - jakirkham
    - msarahan
    - forrestwaters
    - nehaljwani
