{% set version = "23.3.0" %}
{% set constructor_version = "3.3.1" %}
{% set python_version = "3.9.15" %}

package:
  name: conda-standalone
  version: {{ version }}

source:
  - path: ./
  - url: https://github.com/conda/conda/archive/{{ version }}.tar.gz
    sha256: 6e7d8e6247e51847fcf8b264ddfa8eeafc66891db351d5d660ea46c459c46684
    folder: conda_src
    patches:
      - conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch
      - conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch

  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: b000dde0ac8641c92f7342362173968505d4e85845be37655b5b9221cb65f3a8  # [win]
    folder: constructor  # [win]

build:
  number: 0
  ignore_run_exports:
    - '*'

requirements:
  build:
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ version }}
    - conda-package-handling >=1.6
    - tqdm
    - menuinst >=1.4.18  # [win]
  run_constrained:
    - constructor >=3.2.2

test:
  files:
    - testprefix
  commands:
    - ${PREFIX}/standalone_conda/conda.exe -V    # [unix]
    - ${PREFIX}/standalone_conda/conda.exe create -y -p ./env_test zlib tqdm    # [unix]
    - ${PREFIX}/standalone_conda/conda.exe constructor --extract-conda-pkgs --prefix testprefix  # [unix]
    - '%PREFIX%\standalone_conda\conda.exe -V'    # [win]
    - '%PREFIX%\standalone_conda\conda.exe create -y -p env_test zlib tqdm'    # [win]
    - '%PREFIX%\standalone_conda\conda.exe constructor --extract-conda-pkgs --prefix testprefix'  # [win]

about:
  home: https://github.com/AnacondaRecipes/conda-standalone-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.

extra:
  recipe-maintainers:
    - jaimergp
    - jakirkham
    - msarahan
    - forrestwaters
    - nehaljwani
