{% set version = "25.11.0" %}
{% set conda_libmamba_solver_version = "25.11.0" %}
{% set libmambapy_version = "2.3.2" %}
{% set constructor_lower_bound = "3.12.1" %}
{% set menuinst_lower_bound = "2.4.1" %}
{% set python_version = "3.13.13" %}


package:
  name: conda-standalone
  version: {{ version }}

source:
  - url: https://github.com/conda/conda-standalone/archive/{{ version }}.tar.gz
    sha256: ef0453524062e76eaa30b41fb249a54c627761138ca738c0343a8cafd78d975b

  - url: https://github.com/conda/conda/archive/{{ version }}.tar.gz
    sha256: 5995b1ec96c1de0802e41184480933bb3f193a352156c816fb5d151098017407
    folder: conda_src
    patches:
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch"
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch"
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0003-Restrict-search-paths.patch"
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0004-Fix-conda-run.patch"


build:
  number: 0
  ignore_run_exports:
    - '*'
  script_env:
    - PYINSTALLER_CONDARC_DIR={{ RECIPE_DIR }}

requirements:
  build:
    - {{ stdlib('c') }}  # [osx and x86_64]
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ version }}
    - conda-package-handling >=2.3.0
    - conda-package-streaming >=0.9.0
    - menuinst >={{ menuinst_lower_bound }}
    - conda-libmamba-solver ={{ conda_libmamba_solver_version }}
    - libmambapy ={{ libmambapy_version }}
    - archspec >=0.2.3
  run_constrained:
    - constructor >={{ constructor_version }}

test:
  requires:
    - conda ={{ version }}
    - pytest
    - menuinst ={{ menuinst_lower_bound }}
    - ruamel.yaml
  source_files:
    - tests
  commands:
    - pytest -vv -k "not test_uninstallation"
    - test ! -f {{ PREFIX }}/bin/codesign  # [osx]

about:
  home: https://github.com/conda/conda-standalone
  license: LicenseRef-CondaStandalone
  license_file:
    - LICENSE
    - 3rd-party-licenses.json
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.

extra:
  recipe-maintainers:
    - jaimergp
    - jakirkham
    - msarahan
    - forrestwaters
    - nehaljwani
