conda_forge_output_validation: true
build_platform: 
  linux_aarch64: linux_aarch64
  osx_arm64: osx_arm64
provider:
  linux_aarch64: default
  linux_ppc64le: default
  osx_arm64: default
workflow_settings:
  # toggle for storing the conda build_artifacts directory (including the
  # built packages) as an Azure pipeline artifact that can be downloaded
  store_build_artifacts: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
